### ISSUE TITLE
未检测到泄露

### ISSUE THREAD

**Issue by maytrue** [lizhangqu/NDKMemoryLeakSample#1]
您好，android手机未检测到内存泄露？还需要别的改动吗？

只要这句话

# LeakTracer report diff_utc_mono=1498116522.610996

**Comment by hjm1fb** [comment]
试试这个 https://github.com/hjm1fb/AndroidLeakTracerExample

**Comment by maytrue** [comment]
可以检测到泄露的字节数，研究下如何定位到函数名

**Comment by hjm1fb** [comment]
> 可以检测到泄露的字节数，研究下如何定位到函数名

参考文章: https://www.jianshu.com/p/9058f0514416
我目前是直接用addr2line定位, 但发现大型项目集成了包括第三方的十多个左右的so, 并且是通过aar引入的时候,  内存泄露的log会不准. 而小型项目或者检测项目自身的c++代码的内存泄露时, 用addr2line还是可以定位的.
